### ISSUE TITLE
Constructor  and Array

### ISSUE THREAD

**Issue by bendaojiu** [ggicci/jsonla#1]
Two questions:
1. It will throw a error when the string is not started with '{'.
2. When I want to get an array's size, even there is no, it's 'Size()' will return 1.

**Comment by ggicci** [comment]
Try this:

```cpp
Json arr = Json::Parse("[1,2,3,4]");
std::cout << arr.Size();  // 4
```
You have to use `Parse` explicitly since a string value in JSON can be JSON-like `"{ \"number\": 1241 }"`.  That is people may marshal a JSON object to string and use it as the value in another JSON object. See below:

```json
{
  "id": 1,
  "created_at": "2018-01-01T00:00:00Z",
  "config": "{ \"name\": \"some\" }"
}
```
